name: Docs ERPyA
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: erpcya/docss@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './public'
        SPACE_NAME: ${{ secrets.erpya }}
        SPACE_REGION: ${{ secrets.FRA1}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.3R3ZEPXY4DQYECHYOJ6S }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.V6zROjCE9EK/XO6AP+lD8fOlMh+rnxeoAclZRtIPThc }}